// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class Clientes
{
    public Guid Id { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public Guid ZonaId { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();

    public virtual Zonas Zona { get; set; }
}