// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class DetallePedidos
{
    public Guid Id { get; set; }

    public Guid PedidoId { get; set; }

    public Guid ProductoId { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Pedidos Pedido { get; set; }

    public virtual Productos Producto { get; set; }
}