// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class Empleados
{
    public Guid Id { get; set; }

    public string Nombre { get; set; }

    public string Cargo { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<RutasEntrega> RutasEntrega { get; set; } = new List<RutasEntrega>();
}