// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class Pedidos
{
    public Guid Id { get; set; }

    public Guid ClienteId { get; set; }

    public DateTime FechaPedido { get; set; }

    public string Estado { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<DetallePedidos> DetallePedidos { get; set; } = new List<DetallePedidos>();
}