// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class RutasEntrega
{
    public Guid Id { get; set; }

    public Guid ZonaId { get; set; }

    public Guid EmpleadoId { get; set; }

    public DateTime FechaEntrega { get; set; }

    public string Observaciones { get; set; }

    public virtual Empleados Empleado { get; set; }

    public virtual Zonas Zona { get; set; }
}