// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infrastructura.Persistence;

public partial class Usuarios
{
    public Guid Id { get; set; }

    public string NombreUsuario { get; set; }

    public string ClaveHash { get; set; }

    public string Rol { get; set; }
}