// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Dominio.Entities;

public partial class Zonas
{
    public Guid Id { get; set; }

    public string Nombre { get; set; }

    public string Ciudad { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();

    public virtual ICollection<RutasEntrega> RutasEntrega { get; set; } = new List<RutasEntrega>();
}